name: Android Build

on: pull_request
#    branches:
#      - master
    push:
#      branches:
#        - master
      jobs:
        build:
          runs on: ubuntu-latest

          steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Set Up JDK
              uses: actions/setup-java@v4.1.1
              with:
                - java-version: 1.8
                  -
            - name: Run Tests
              run: ./gradlew test

            - name: Build Project
              run: ./gradlew assemble
              with:
                name: AndroidCiCd.apk
                path: app/build/outputs/apk/debug/app-debug.apk
